"""
Phase 2 — re-validate the answers we previously generated by AI.

For every physics question in any nsejs_*_classified.json where
`correct_source == 'ai_solved'` (text-only, no figure context), re-solve with
a STRICTER prompt:

  - reason step-by-step
  - if the computed value matches one option exactly, answer that letter
  - if computed value isn't in the choices (or you're not sure), return null
  - if you'd need to see a figure to decide, return null

The new answer wins if Claude was confident either way. If Claude returns
null, we mark `parse_status='needs_review'` on that record so it won't appear
in practice (until a human or future pass corrects it).

Skips `ai_solved_figure` rows — those went through Vision with the figure
attached and are already as good as we can get.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

env_path = Path(__file__).resolve().parent.parent.parent / '.env'
if env_path.exists():
    for line in env_path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        k, v = line.split('=', 1)
        os.environ.setdefault(k.strip(), v.strip())

from anthropic import Anthropic


SOLVE_MODEL = 'claude-sonnet-4-20250514'
HERE = Path(__file__).parent

SYSTEM_PROMPT = """You are double-checking previously AI-generated MCQ answers
for an Indian Class 9 student's NSEJS physics practice bank. Be strict.

For each question I send:
  1. Reason step by step inside <work> tags. Compute symbolically when you
     can; check units; sanity-check magnitudes.
  2. If your computed answer EXACTLY matches one of the four options
     (within reasonable rounding), output <answer>a|b|c|d</answer>.
  3. If your computed answer doesn't match any option, OR the question is
     ambiguous, OR you'd need to see a figure to decide:
     output <answer>none</answer>.
  4. End with <confidence>high|medium|low</confidence>.

Rules:
  - Don't pick the closest option just to give an answer. If your answer is
    "1.54 V" and choices are 2/4/6/8, output none — don't round to 2.
  - "high" only when your reasoning is unambiguous and exactly one option
    fits. Otherwise "medium" or "low".

You MUST end every response with the <answer> and <confidence> tags."""


_TAG_RE = re.compile(r'<(\w+)>(.*?)</\1>', re.DOTALL)


def revalidate_one(client: Anthropic, q: dict) -> dict:
    user_text = (
        f'Question {q["number"]}: {q["body"]}\n\n'
        + '\n'.join(f'({L}) {q["choices"].get(L, "")}' for L in 'abcd')
    )
    resp = client.messages.create(
        model=SOLVE_MODEL,
        max_tokens=2500,
        system=SYSTEM_PROMPT,
        messages=[{'role': 'user', 'content': user_text}],
    )
    text = resp.content[0].text.strip()
    tags = {m.group(1): m.group(2).strip() for m in _TAG_RE.finditer(text)}
    raw_answer = tags.get('answer', '').lower()
    if raw_answer == 'none' or raw_answer not in ('a', 'b', 'c', 'd'):
        ans = None
    else:
        ans = raw_answer
    return {
        'correct': ans,
        'confidence': tags.get('confidence', 'medium').lower() or 'medium',
    }


def process_slug(slug: str, dry_run: bool = False) -> dict:
    path = HERE / f'nsejs_{slug}_classified.json'
    if not path.exists():
        return {'slug': slug, 'error': 'no classified file'}
    data = json.loads(path.read_text())

    targets = [
        q for q in data['questions']
        if q.get('subject') == 'physics'
        and q.get('correct_source') == 'ai_solved'
        and q.get('correct')
    ]
    if not targets:
        return {'slug': slug, 'processed': 0, 'kept': 0, 'changed': 0, 'demoted': 0}

    client = Anthropic()
    kept = 0
    changed = 0
    demoted = 0

    for q in targets:
        old = q['correct']
        try:
            res = revalidate_one(client, q)
        except Exception as e:
            print(f'  [{slug} Q{q["number"]}] error: {e}')
            continue
        new = res['correct']
        conf = res['confidence']
        if new is None:
            # Strict prompt couldn't solve it — flag for review.
            q['parse_status'] = 'needs_review'
            q['correct_confidence'] = 'low'
            demoted += 1
            print(f'  [{slug} Q{q["number"]}] demoted (was {old}, now unsolvable)')
        elif new.upper() == old.upper():
            q['correct_confidence'] = conf
            kept += 1
        else:
            # Trust the new strict answer
            q['correct'] = new
            q['correct_source'] = 'ai_solved_revalidated'
            q['correct_confidence'] = conf
            changed += 1
            print(f'  [{slug} Q{q["number"]}] changed: {old} -> {new} (conf={conf})')

    if not dry_run:
        path.write_text(json.dumps(data, indent=2, ensure_ascii=False))
    return {
        'slug': slug,
        'processed': len(targets),
        'kept': kept, 'changed': changed, 'demoted': demoted,
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('slugs', nargs='*')
    ap.add_argument('--dry-run', action='store_true')
    args = ap.parse_args()

    if args.slugs:
        slugs = args.slugs
    else:
        slugs = sorted(p.stem.replace('nsejs_', '').replace('_classified', '')
                       for p in HERE.glob('nsejs_*_classified.json'))

    print(f'Re-validating across {len(slugs)} files (dry_run={args.dry_run})')
    summary = []
    for slug in slugs:
        print(f'\n=== {slug} ===')
        r = process_slug(slug, args.dry_run)
        summary.append(r)

    print('\n=== Summary ===')
    print(f'{"slug":<24} {"proc":>5} {"kept":>5} {"chg":>4} {"demoted":>8}')
    g = {'p': 0, 'k': 0, 'c': 0, 'd': 0}
    for r in summary:
        if 'error' in r:
            continue
        print(f'{r["slug"]:<24} {r["processed"]:>5} {r["kept"]:>5} {r["changed"]:>4} {r["demoted"]:>8}')
        g['p'] += r['processed']
        g['k'] += r['kept']
        g['c'] += r['changed']
        g['d'] += r['demoted']
    print(f'{"TOTAL":<24} {g["p"]:>5} {g["k"]:>5} {g["c"]:>4} {g["d"]:>8}')


if __name__ == '__main__':
    main()
